Header
bogachenkopetr/merkury pull request #1
Opened 2020-06-15 14:59 UTC by bogachenkopetr

2020-06-16 07:37 UTC, abahachenka requested changes
В папке img удалить Merkury_Landing Page.psd.
В папке fonts удалить лишние шрифты (кроме папки roboto).
Ну а в целом, молоток!

2020-06-16 07:37 UTC, abahachenka commented on index.html
> +    <script src="https://kit.fontawesome.com/d2af1d22a9.js" crossorigin="anonymous"></script> -->
Если это больше не нужно, то надо удалить

2020-06-16 07:37 UTC, abahachenka commented on index.html
> +
Лишняя пустая строка

2020-06-16 07:37 UTC, abahachenka commented on scss/common.scss
> +body {
Добавить пустую строку до body

2020-06-16 07:37 UTC, abahachenka commented on scss/fonts.scss
> +@font-face {
Все отлично. Но в папке fonts много лишних файлов. Удали оттуда все, кроме папки roboto

2020-06-16 07:37 UTC, abahachenka commented on scss/header.scss
> +    height: 1100px;/*???*/
Разберись с комментарием. Если ты не уверен с высотой, то вроде все работает.

2020-06-16 07:37 UTC, abahachenka commented on scss/header.scss
> +
Лишняя строка

2020-06-16 07:37 UTC, abahachenka commented on scss/style.scss
> +@import 'fonts';
Должен идти самым первым.

2020-06-16 18:11 UTC, bogachenkopetr commented
внес исправления

2020-06-17 08:29 UTC, abahachenka commented
В файле fonts.scss твои ттф-ки подключаются как 'roboto-bold-webfont.ttf', а сами файлы называются иначе. Нужно файлы переименовать так, как указано в font-face. Потому что сейчас твой css не может найти эти файлы.

2020-06-17 12:43 UTC, bogachenkopetr commented
внес исправления

2020-06-17 14:28 UTC, merged