внес исправления в секции header и features
bogachenkopetr/merkury pull request #2
Opened 2020-06-21 09:38 UTC by bogachenkopetr

2020-06-21 13:25 UTC, abahachenka commented
480:
1) Сделай логотип немножко меньше. Он сейчас сильно выбивается из общего дизайна - слишком большой.

2) Бургер тоже бы уменьшить, хотя бы до font-size: 30px;

3) Кнопки See More и Get Started должны полностью быть одинаковыми по дизайну, кроме цвета.

4) Крестик в меню криво стоит.
<img width="441" alt="Screen Shot 2020-06-21 at 16 23 03" src="https://user-images.githubusercontent.com/53353277/85225737-df131180-b3db-11ea-8425-62f6b2ed060b.png">

2020-06-21 13:56 UTC, abahachenka requested changes

2020-06-21 13:56 UTC, abahachenka commented on scss/features.scss
> +
ненужная пустая строка

2020-06-21 13:56 UTC, abahachenka commented on scss/features.scss
> +}
это внести в предыдущий блок

2020-06-21 13:56 UTC, abahachenka commented on scss/features.scss
> +
если блок только начался пустая строка не нужна

2020-06-21 13:56 UTC, abahachenka commented on scss/features.scss
> +    a {
На будущее, сейчас можешь не менять ничего. НО! У тебя слишком много привязки к тегам. Лучше это делать через классы. Потому что, если, например, понадобится поменять `a` на `button`, то придется обновлять и html и css.

2020-06-21 13:56 UTC, abahachenka commented on scss/header.scss
> +    max-height: 1100px;
тут все таки лучше вернуть height и подстроить ее под каждый media-запрос

2020-06-21 13:56 UTC, abahachenka commented on scss/header.scss
> +        padding: 8px;
странное значение. почему не круглое? сюда бы вернуть левый-правый 20px

2020-06-21 13:56 UTC, abahachenka commented on scss/header.scss
> +        margin-left: 20px;
это лучше делать через padding для li

2020-06-21 13:56 UTC, abahachenka commented on scss/header.scss
> +
лишняя пустая строка

2020-06-22 08:46 UTC, bogachenkopetr commented
внес исправления по замечаниям

2020-06-24 11:27 UTC, merged